In [28]:
import numpy as np
import pickle as pkl
import networkx as nx
import scipy.sparse as sp
from scipy.sparse.linalg.eigen.arpack import eigsh
import sys
def load_cora():
    names = ['x']
    with open("E:/ltr_do/deep_learn/GCN/GCN_resource/gcn/gcn/data/ind.cora.x", 'rb') as f:
        if sys.version_info > (3, 0):
            print(f)  # <_io.BufferedReader name='data/ind.cora.x'>
            data = pkl.load(f, encoding='latin1') # Latin1是ISO-8859-1的别名
            print(type(data)) #<class 'scipy.sparse.csr.csr_matrix'>
            print(data.shape)   #(140, 1433)-ind.cora.x是140行，1433列的
            print(data.toarray())
            print(data) # 稀疏矩阵用坐标标明

In [29]:
load_cora()

<_io.BufferedReader name='E:/ltr_do/deep_learn/GCN/GCN_resource/gcn/gcn/data/ind.cora.x'>
<class 'scipy.sparse.csr.csr_matrix'>
(140, 1433)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
  (0, 19)	1.0
  (0, 81)	1.0
  (0, 146)	1.0
  (0, 315)	1.0
  (0, 774)	1.0
  (0, 877)	1.0
  (0, 1194)	1.0
  (0, 1247)	1.0
  (0, 1274)	1.0
  (1, 19)	1.0
  (1, 88)	1.0
  (1, 149)	1.0
  (1, 212)	1.0
  (1, 233)	1.0
  (1, 332)	1.0
  (1, 336)	1.0
  (1, 359)	1.0
  (1, 472)	1.0
  (1, 507)	1.0
  (1, 548)	1.0
  (1, 687)	1.0
  (1, 763)	1.0
  (1, 808)	1.0
  (1, 889)	1.0
  (1, 1058)	1.0
  :	:
  (138, 1263)	1.0
  (138, 1274)	1.0
  (138, 1290)	1.0
  (138, 1307)	1.0
  (138, 1406)	1.0
  (139, 1)	1.0
  (139, 41)	1.0
  (139, 187)	1.0
  (139, 212)	1.0
  (139, 357)	1.0
  (139, 404)	1.0
  (139, 464)	1.0
  (139, 505)	1.0
  (139, 507)	1.0
  (139, 581)	1.0
  (139, 635)	1.0
  (139, 874)	1.0
  (139, 988)	1.0
  (139, 1071)	1

In [38]:
def view_all_cora():
    names = ['x', 'y', 'tx', 'ty', 'allx', 'ally', 'graph']
    objects = []
    for i in range(len(names)):
        with open("E:/ltr_do/deep_learn/GCN/GCN_resource/gcn/gcn/data/ind.{}.{}".format("cora", names[i]), 'rb') as f:
            if sys.version_info > (3, 0): # Python中版本获取Python版本号 
                objects.append(pkl.load(f, encoding='latin1'))
            else:
                objects.append(pkl.load(f))

    return tuple(objects)

In [39]:
x, y, tx, ty, allx, ally, graph = view_all_cora()

In [139]:
for i in ally :
    if i[0] == i[1] and i[1] == i[2] and i[2] == i[3] and i[3] == i[4] and i[4] == i[5]  :#and i[5] == i[6] :
        print(i)

[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0 0 0 1]
[0 0 0 0

In [44]:
print(x.shape)
print(x)

(140, 1433)
  (0, 19)	1.0
  (0, 81)	1.0
  (0, 146)	1.0
  (0, 315)	1.0
  (0, 774)	1.0
  (0, 877)	1.0
  (0, 1194)	1.0
  (0, 1247)	1.0
  (0, 1274)	1.0
  (1, 19)	1.0
  (1, 88)	1.0
  (1, 149)	1.0
  (1, 212)	1.0
  (1, 233)	1.0
  (1, 332)	1.0
  (1, 336)	1.0
  (1, 359)	1.0
  (1, 472)	1.0
  (1, 507)	1.0
  (1, 548)	1.0
  (1, 687)	1.0
  (1, 763)	1.0
  (1, 808)	1.0
  (1, 889)	1.0
  (1, 1058)	1.0
  :	:
  (138, 1263)	1.0
  (138, 1274)	1.0
  (138, 1290)	1.0
  (138, 1307)	1.0
  (138, 1406)	1.0
  (139, 1)	1.0
  (139, 41)	1.0
  (139, 187)	1.0
  (139, 212)	1.0
  (139, 357)	1.0
  (139, 404)	1.0
  (139, 464)	1.0
  (139, 505)	1.0
  (139, 507)	1.0
  (139, 581)	1.0
  (139, 635)	1.0
  (139, 874)	1.0
  (139, 988)	1.0
  (139, 1071)	1.0
  (139, 1230)	1.0
  (139, 1231)	1.0
  (139, 1258)	1.0
  (139, 1263)	1.0
  (139, 1274)	1.0
  (139, 1393)	1.0


In [45]:
print(y.shape)
print(y)

(140, 7)
[[0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]
 [0 0

In [47]:
print(tx.shape)
print(tx)

(1000, 1433)
  (0, 311)	1.0
  (0, 314)	1.0
  (0, 353)	1.0
  (0, 505)	1.0
  (0, 510)	1.0
  (0, 621)	1.0
  (0, 1075)	1.0
  (0, 1132)	1.0
  (0, 1171)	1.0
  (0, 1226)	1.0
  (0, 1230)	1.0
  (0, 1301)	1.0
  (0, 1379)	1.0
  (0, 1389)	1.0
  (0, 1392)	1.0
  (1, 78)	1.0
  (1, 121)	1.0
  (1, 228)	1.0
  (1, 505)	1.0
  (1, 510)	1.0
  (1, 617)	1.0
  (1, 662)	1.0
  (1, 931)	1.0
  (1, 988)	1.0
  (1, 993)	1.0
  :	:
  (998, 1240)	1.0
  (998, 1258)	1.0
  (998, 1263)	1.0
  (998, 1306)	1.0
  (998, 1314)	1.0
  (999, 30)	1.0
  (999, 65)	1.0
  (999, 432)	1.0
  (999, 548)	1.0
  (999, 570)	1.0
  (999, 610)	1.0
  (999, 690)	1.0
  (999, 720)	1.0
  (999, 724)	1.0
  (999, 749)	1.0
  (999, 763)	1.0
  (999, 993)	1.0
  (999, 1058)	1.0
  (999, 1143)	1.0
  (999, 1150)	1.0
  (999, 1170)	1.0
  (999, 1177)	1.0
  (999, 1205)	1.0
  (999, 1274)	1.0
  (999, 1392)	1.0


In [48]:
print(ty.shape)
print(ty)

(1000, 7)
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]]


In [49]:
print(allx.shape)
print(allx)

(1708, 1433)
  (0, 19)	1.0
  (0, 81)	1.0
  (0, 146)	1.0
  (0, 315)	1.0
  (0, 774)	1.0
  (0, 877)	1.0
  (0, 1194)	1.0
  (0, 1247)	1.0
  (0, 1274)	1.0
  (1, 19)	1.0
  (1, 88)	1.0
  (1, 149)	1.0
  (1, 212)	1.0
  (1, 233)	1.0
  (1, 332)	1.0
  (1, 336)	1.0
  (1, 359)	1.0
  (1, 472)	1.0
  (1, 507)	1.0
  (1, 548)	1.0
  (1, 687)	1.0
  (1, 763)	1.0
  (1, 808)	1.0
  (1, 889)	1.0
  (1, 1058)	1.0
  :	:
  (1706, 1236)	1.0
  (1706, 1242)	1.0
  (1706, 1320)	1.0
  (1706, 1337)	1.0
  (1707, 4)	1.0
  (1707, 118)	1.0
  (1707, 153)	1.0
  (1707, 180)	1.0
  (1707, 228)	1.0
  (1707, 699)	1.0
  (1707, 701)	1.0
  (1707, 719)	1.0
  (1707, 750)	1.0
  (1707, 758)	1.0
  (1707, 810)	1.0
  (1707, 911)	1.0
  (1707, 1177)	1.0
  (1707, 1233)	1.0
  (1707, 1251)	1.0
  (1707, 1257)	1.0
  (1707, 1262)	1.0
  (1707, 1299)	1.0
  (1707, 1325)	1.0
  (1707, 1386)	1.0
  (1707, 1397)	1.0


In [91]:
print(ally.shape)
# print(ally[:10, :])
for i in ally :
    if i[0] == i[1] and i[1] == i[2] and i[2] == i[3] and i[3] == i[4] and i[4] == i[5] and i[5] == i[6] :
        print(i)

(1708, 7)


In [53]:
print(type(graph))

<class 'collections.defaultdict'>


In [70]:
for i in list(graph) :
    print(graph[i])

[633, 1862, 2582]
[2, 652, 654]
[1986, 332, 1666, 1, 1454]
[2544]
[2176, 1016, 2176, 1761, 1256, 2175]
[1629, 2546, 1659, 1659]
[1416, 1602, 1042, 373]
[208]
[281, 1996, 269]
[2614, 723, 723]
[476, 2545]
[1655, 1839]
[2661, 1001, 1318, 2662]
[1810, 1701]
[2034, 2075, 158, 2077, 2668]
[2367, 1093, 1090, 1271, 1093]
[2444, 1632, 970, 2642]
[24, 2140, 1316, 1315, 927]
[2082, 139, 1786, 1560, 2145]
[1939]
[1072, 2374, 2375, 2269, 2270]
[1043, 2310]
[1703, 1702, 2238, 39, 1234]
[2159]
[1701, 2139, 1636, 17, 2141, 598, 201]
[1344, 2011, 1301, 2317]
[2454, 2455, 123, 99, 122]
[1810, 606, 2360, 2578]
[1687]
[963, 2645]
[1358, 1416, 2162, 697, 2343, 738]
[1594]
[1973, 279, 518, 1850]
[2119, 911, 588, 1051, 2120, 286, 2040, 2121, 698]
[1358]
[1296, 1913, 895]
[1146, 1640, 1505, 2106, 1781, 2094, 1552, 2107]
[2427, 1190, 60]
[429, 1160, 862, 863, 862]
[1634, 1965, 1349, 1532, 1522, 22, 2357]
[507, 866, 1364]
[1914, 644, 175, 596]
[1372, 87]
[963, 2399, 2400, 152, 1653, 1530]
[1582, 2624, 2701, 26

In [71]:
def parse_index_file(filename):
    """Parse index file."""
    index = []
    for line in open(filename):
        index.append(int(line.strip()))
    return index
test_idx_reorder = parse_index_file("E:/ltr_do/deep_learn/GCN/GCN_resource/gcn/gcn/data/ind.{}.test.index".format("cora"))
test_idx_range = np.sort(test_idx_reorder)

In [107]:
print(test_idx_reorder)
# print(len(test_idx_range)) # 1708 -  2707  1000个
print((test_idx_range)) 

[2692, 2532, 2050, 1715, 2362, 2609, 2622, 1975, 2081, 1767, 2263, 1725, 2588, 2259, 2357, 1998, 2574, 2179, 2291, 2382, 1812, 1751, 2422, 1937, 2631, 2510, 2378, 2589, 2345, 1943, 1850, 2298, 1825, 2035, 2507, 2313, 1906, 1797, 2023, 2159, 2495, 1886, 2122, 2369, 2461, 1925, 2565, 1858, 2234, 2000, 1846, 2318, 1723, 2559, 2258, 1763, 1991, 1922, 2003, 2662, 2250, 2064, 2529, 1888, 2499, 2454, 2320, 2287, 2203, 2018, 2002, 2632, 2554, 2314, 2537, 1760, 2088, 2086, 2218, 2605, 1953, 2403, 1920, 2015, 2335, 2535, 1837, 2009, 1905, 2636, 1942, 2193, 2576, 2373, 1873, 2463, 2509, 1954, 2656, 2455, 2494, 2295, 2114, 2561, 2176, 2275, 2635, 2442, 2704, 2127, 2085, 2214, 2487, 1739, 2543, 1783, 2485, 2262, 2472, 2326, 1738, 2170, 2100, 2384, 2152, 2647, 2693, 2376, 1775, 1726, 2476, 2195, 1773, 1793, 2194, 2581, 1854, 2524, 1945, 1781, 1987, 2599, 1744, 2225, 2300, 1928, 2042, 2202, 1958, 1816, 1916, 2679, 2190, 1733, 2034, 2643, 2177, 1883, 1917, 1996, 2491, 2268, 2231, 2471, 1919, 1909, 201

In [125]:
features = sp.vstack((allx, tx)).tolil() # 合起来装换成List of Lists format的格式 
features

<2708x1433 sparse matrix of type '<class 'numpy.float32'>'
	with 49216 stored elements in List of Lists format>

In [119]:
labels = np.vstack((ally, ty))

In [126]:
for i in labels:
    if i[0] == i[1] and i[1] == i[2] and i[2] == i[3] and i[3] == i[4] and i[4] == i[5] and i[5] == i[6] :
        print(i)

In [116]:
X = np.array([[1,0,0], [0, 1, 0],[0, 0, 1]])
lst1 = [2, 1]
lst2 = [1, 2]
X

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [117]:
X[lst1, :] = X[lst2, :]
X

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [128]:
import tensorflow as tf
x = tf.constant([1, 2, 3])
sess = tf.Session()
print(sess.run(tf.add_n([x, x]))) # [2 4 6]


[2 4 6]


In [143]:
import tensorflow as tf
x = tf.constant([[1, 2], [3, 4]],dtype=tf.float32)
with tf.Session() as sess:
    print(sess.run(tf.nn.l2_loss(x))) # (1 + 4 + 9 + 16) / 2 = 30 / 2  = 15

15.0


In [151]:
class Parent(object):
    def __init__(self, name):
        self.name = name        
        print("__class__:", self.__class__) 
        print("create an instance of:", self.__class__.__name__) 
        print("create an instance of:", self.__class__.__name__.lower()) 
        print("name attribute is:", self.name)


In [152]:
x = Parent("haha")

__class__: <class '__main__.Parent'>
create an instance of: Parent
create an instance of: parent
name attribute is: haha
