In [2]:
from scipy import sparse
import numpy as np

In [3]:
row = np.array([0, 3, 1, 0])
col = np.array([0, 3, 1, 2])
data = np.array([6, 5, 7, 8])

In [4]:
X = sparse.csr_matrix((data, (row, col)), shape=(4, 4))

In [20]:
type(X)

scipy.sparse.csr.csr_matrix

In [6]:
X.toarray()

array([[6, 0, 8, 0],
       [0, 7, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 5]], dtype=int32)

In [42]:
t = X.tolil()

In [64]:
for i in t.data:
    print(i)

[6, 8]
[7]
[]
[5]


In [67]:
t = X.tocoo()

In [78]:
import numpy as np
print(t.row)
print(t.col)
x = np.vstack([t.row, t.col])
print(x)
print(x.transpose())

[0 0 1 3]
[0 2 1 3]
[[0 0 1 3]
 [0 2 1 3]]
[[0 0]
 [0 2]
 [1 1]
 [3 3]]
