In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
np.random.seed(666)
x = np.random.random(size = (1000, 10))

In [3]:
true_theta = np.arange(1, 12, dtype=int)

In [4]:
true_theta

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
X_b = np.hstack([np.ones((len(x), 1)), x])
X_b.shape

(1000, 11)

In [6]:
y = X_b.dot(true_theta) + np.random.normal(size=1000)

In [7]:
def L(theta, X_b, y):
    try:
        return np.sum( (X_b.dot(theta) - y)**2 )*2/len(y)
    except:
        return float('inf')

In [8]:
def dL_math(theta, X_b, y):
    return X_b.T.dot(X_b.dot(theta) - y) * 2 / len(y)

In [13]:
def dL_debug(theta, X_b, y, epsilon = 0.0001):
    res = np.empty(len(theta))
    for i in range(len(theta)):
        theta1 = theta.copy()
        theta1[i] += epsilon
        theta2 = theta.copy()
        theta2[i] -= epsilon
        res[i] = (L(theta1, X_b, y) - L(theta2, X_b, y)) / (2 * epsilon)
    return res

In [14]:
def gradicent_descent(dL, X_b, y, initial_theta, eta = 0.01, n_iter = 1e4, epsilon = 1e-8):
    
    theta = initial_theta
    
    while n_iter > 0:
        n_iter -= 1
        gradicent = dL(theta, X_b, y)
        last_theta = theta
        theta = theta - eta * gradicent
        if abs( L(theta, X_b, y) - L(last_theta, X_b, y)) < epsilon:
            break;
    
    return theta
            

In [15]:
initial_theta = np.zeros(X_b.shape[1])
gradicent_descent(dL_math, X_b, y, initial_theta, eta=0.01)

array([ 1.1251597 ,  2.05312521,  2.91522497,  4.11895968,  5.05002117,
        5.90494046,  6.97383745,  8.00088367,  8.86213468,  9.98608331,
       10.90529198])

In [16]:
initial_theta = np.zeros(X_b.shape[1])
gradicent_descent(dL_debug, X_b, y, initial_theta, eta=0.01)

array([ 1.07100036,  2.06026457,  2.92714777,  4.13171222,  5.06055108,
        5.91417668,  6.98567927,  8.00953517,  8.87463505,  9.99561426,
       10.9168092 ])